version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    ignore:
      # Keep `openai` below 1.0.0.
      - dependency-name: openai
        update-types: ['version-update:semver-major']
    groups:
      python:
        patterns: ['*']

  - package-ecosystem: actions
    directory: '/'
    schedule:
      interval: daily
    groups:
      actions:
        patterns: ['*']
