version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    open-pull-requests-limit: 100

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
