#!/usr/bin/env bash

run_one() {
    python <<'EOF'
import embed
for j in range(100):
    embed.embed_one_req(f"Testing rate limiting, {j=}.")
EOF
}

for i in {1..100}; do
    run_one &
done

sleep 1000
