#!/bin/sh
set -eux

version="${1:?Graphviz version to install not specified}"

mkdir -p -- ~/src
cd -- ~/src

url_prefix='https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases'
wget -- "$url_prefix/$version/graphviz-$version.tar.xz"
tar xf "graphviz-$version.tar.xz"
cd "graphviz-$version/"

cpu_count="$(nproc)"
job_count="$((cpu_count * 4 / 3))"

./configure
make -j "$job_count"
sudo make install  # Assumes sudo requires no password.
